app:
    currency: IDR
    timezone: Asia/Jakarta
    welcome-text: Hello World from Tedy, are you ready ? this is from properties

cloud:
    api-key: ${CLOUD_KEY}

server:
    port: 8070

logging:
  level:
    '[com.example.practice]' : DEBUG

spring:
  datasource:
    hikari:
      connection-timeout: 600000
      idle-timeout: 600000
      max-lifetime: 1800000
      maximum-pool-size: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot
    username: root
    password: root

  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      


---
spring:
  config:
    activate:
      on-profile:
      - cobain
      
app:
    currency: IDR
    timezone: Asia/Jakarta
    welcome-text: Hello World from Tedy, are you ready ? this is from properties

cloud:
    api-key: ${CLOUD_KEY}

server:
    port: 8090
